// Template buku — preset untuk berbagai jenis penggunaan.
// Memudahkan user baru paham apa yang harus dicatat & kategori apa yang relevan.

export const BOOK_TEMPLATES = [
  {
    id: "pribadi",
    icon: "📒",
    name: "Pribadi / Keluarga",
    description: "Catat pengeluaran rumah tangga sehari-hari, gaji, tagihan",
    defaultBookName: "Keuangan Bulanan",
    openingBalanceHint: "Saldo rekening / cash saat mulai mencatat",
    suggestedIncomeCategories: ["pendapatan", "hadiah", "pinjaman"],
    suggestedExpenseCategories: [
      "konsumsi",
      "listrik-air",
      "transport",
      "internet-pulsa",
      "pendidikan",
      "kesehatan",
    ],
    tips: "Catat pengeluaran sehari-hari biar tahu uang habis ke mana. Saldo awal = sisa uang Anda sekarang.",
  },
  {
    id: "warung",
    icon: "🏪",
    name: "Warung / Sembako",
    description: "Toko kelontong, sembako, jualan harian",
    defaultBookName: "Warung",
    openingBalanceHint: "Modal usaha awal (uang yang sudah Anda siapkan)",
    suggestedIncomeCategories: [
      "penjualan",
      "modal-awal",
      "modal-tambahan",
      "pinjaman-usaha",
    ],
    suggestedExpenseCategories: [
      "bahan-baku",
      "kemasan",
      "sewa-tempat",
      "listrik-air",
      "gaji-karyawan",
      "operasional",
    ],
    tips: "Tutup toko = tap (+) catat total penjualan hari ini. Beli stok = catat kategori 'Bahan Baku / Stok'.",
  },
  {
    id: "konter",
    icon: "📱",
    name: "Konter Pulsa & Aksesoris",
    description: "Jualan pulsa, paket data, aksesoris HP, voucher game",
    defaultBookName: "Konter",
    openingBalanceHint: "Modal awal + saldo deposit pulsa pertama",
    suggestedIncomeCategories: [
      "penjualan",
      "modal-awal",
      "modal-tambahan",
      "pinjaman-usaha",
    ],
    suggestedExpenseCategories: [
      "bahan-baku",
      "internet-pulsa",
      "sewa-tempat",
      "listrik-air",
      "operasional",
      "promosi",
    ],
    tips: "Deposit pulsa = 'Bahan Baku'. Catat penjualan harian (total), bukan per transaksi.",
  },
  {
    id: "bangunan",
    icon: "🏗️",
    name: "Proyek Bangunan / Renovasi",
    description: "Pembangunan rumah, renovasi, proyek konstruksi",
    defaultBookName: "Pembangunan Rumah",
    openingBalanceHint: "Dana yang sudah disiapkan untuk proyek ini",
    suggestedIncomeCategories: [
      "modal-awal",
      "modal-tambahan",
      "pinjaman",
      "hadiah",
    ],
    suggestedExpenseCategories: [
      "material",
      "tukang",
      "transport",
      "konsumsi",
      "perawatan",
    ],
    tips: "Catat tiap belanja material dengan qty × harga (mis. 40 papan × Rp 30.000) supaya bisa dianalisis kemudian.",
  },
  {
    id: "jasa",
    icon: "💇",
    name: "Usaha Jasa",
    description: "Laundry, salon, cuci motor, tukang, jasa lainnya",
    defaultBookName: "Usaha Jasa",
    openingBalanceHint: "Modal awal usaha",
    suggestedIncomeCategories: [
      "penjualan",
      "modal-awal",
      "modal-tambahan",
    ],
    suggestedExpenseCategories: [
      "operasional",
      "bahan-baku",
      "gaji-karyawan",
      "sewa-tempat",
      "listrik-air",
      "internet-pulsa",
      "promosi",
    ],
    tips: "Setiap akhir hari catat total pendapatan jasa. Beli sabun/deterjen/bahan habis pakai = 'Operasional Usaha'.",
  },
  {
    id: "tani-ternak",
    icon: "🐟",
    name: "Tani / Ternak / Perikanan",
    description: "Perikanan, ternak ayam, sayur, pertanian dengan panen periodik",
    defaultBookName: "Usaha Tani",
    openingBalanceHint: "Modal awal usaha tani/ternak",
    suggestedIncomeCategories: [
      "penjualan",
      "modal-awal",
      "modal-tambahan",
      "pinjaman-usaha",
    ],
    suggestedExpenseCategories: [
      "bahan-baku",
      "operasional",
      "gaji-karyawan",
      "transport",
      "perawatan",
    ],
    tips: "Pakan/pupuk = 'Bahan Baku / Stok'. Hasil panen masuk sebagai 'Penjualan / Omzet'. Tracking modal vs hasil panen.",
  },
  {
    id: "tabungan",
    icon: "🎯",
    name: "Tabungan Tujuan",
    description: "Tabungan haji, sekolah anak, kendaraan, nikah, dll",
    defaultBookName: "Tabungan",
    openingBalanceHint: "Yang sudah terkumpul sebelum mulai mencatat",
    suggestedIncomeCategories: [
      "modal-tambahan",
      "hadiah",
      "pendapatan",
    ],
    suggestedExpenseCategories: ["lain-out"],
    tips: "Setiap setor tabungan = Kas Masuk kategori 'Modal Tambahan'. Saldo = jumlah uang yang sudah terkumpul.",
  },
  {
    id: "custom",
    icon: "🆓",
    name: "Custom / Kosong",
    description: "Mulai dari kosong, atur sendiri sesuai kebutuhan",
    defaultBookName: "",
    openingBalanceHint: "Jumlah uang yang sudah ada (opsional)",
    suggestedIncomeCategories: [],
    suggestedExpenseCategories: [],
    tips: "Cocok kalau Anda mau atur sendiri tanpa preset. Semua kategori tetap tersedia.",
  },
];

export function getTemplate(id) {
  return BOOK_TEMPLATES.find((t) => t.id === id) || null;
}
